name             'phpsysinfo-cookbook'
maintainer       'Greg Palmier'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures phpsysinfo-cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.0'
depends		 'apache2'
depends		 'xml'
depends		 'php'
depends		 'git'
